# Generated by Django 3.1 on 2020-12-22 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('d', 'DEVELOPMENT'), ('s', 'SIT'), ('u', 'UAT'), ('st', 'STAGING/PRE-PROD'), ('p', 'PRODUCTION')], max_length=70)),
                ('platform', models.CharField(choices=[('m', 'MacOs'), ('l', 'LINUX'), ('w', 'WINDOWS')], max_length=50)),
                ('database', models.CharField(choices=[('pst', 'POSTGRESQL'), ('md', 'MariaDB'), ('my', 'MySQL'), ('o', 'Oracle'), ('ms', 'MS SQL Server'), ('sl', 'SQLite3'), ('cd', 'CosmosDB'), ('mg', 'MongoDB')], max_length=100)),
                ('run_stack', models.CharField(max_length=100)),
                ('web_server', models.CharField(max_length=100)),
                ('ip_servername', models.IntegerField()),
                ('hardware', models.CharField(choices=[('ps', 'PHISICAL_SERVER'), ('vm', 'VIRTUAL MACHINE')], max_length=150)),
                ('product_app', models.CharField(max_length=300)),
                ('provider', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('brd', models.ImageField(blank=True, upload_to='environment/brd/')),
            ],
            options={
                'ordering': ['stage', 'platform', 'database'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentBulkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='environment/bulkupload/')),
            ],
        ),
    ]
